import shutil
import subprocess
import sys

from pathlib import Path

# VHDL Imports
from hdl_registers.generator.vhdl.axi_lite.wrapper import VhdlAxiLiteWrapperGenerator
from hdl_registers.generator.vhdl.record_package import VhdlRecordPackageGenerator
from hdl_registers.generator.vhdl.register_package import VhdlRegisterPackageGenerator

from hdl_registers.generator.vhdl.simulation.check_package import (
    VhdlSimulationCheckPackageGenerator,
)

from hdl_registers.generator.vhdl.simulation.read_write_package import (
    VhdlSimulationReadWritePackageGenerator,
)

from hdl_registers.generator.vhdl.simulation.wait_until_package import (
    VhdlSimulationWaitUntilPackageGenerator,
)

# C++ Imports
from hdl_registers.generator.cpp.header import CppHeaderGenerator
from hdl_registers.generator.cpp.implementation import CppImplementationGenerator
from hdl_registers.generator.cpp.interface import CppInterfaceGenerator

# Rust Imports (custom generator, see rust_generator.py)
from rust_generator import RustRegisterGenerator

from hdl_registers.parser.toml import from_toml

from hdl_registers import __version__ as hdl_registers_version
from hdl_registers.generator.register_code_generator import RegisterCodeGenerator


# By default every generated file header carries a "Generated <timestamp> ... at Git commit <sha>"
# line plus a "Register hash <sha>" line. Both are volatile in committed artifacts: the timestamp
# changes on every run, and the hash changes on any register-definition edit (including
# description-only edits), churning all generated headers. Drop both, keeping only the tool and
# generator version lines. This is safe here because we always call .create() (never
# .create_if_needed()), so regeneration is never gated on the hash line.
def _stable_generated_source_info(self) -> list[str]:
    return [
        f"This file is automatically generated by hdl-registers version {hdl_registers_version}.",
        f"Code generator {self.__class__.__name__} version {self.__version__}.",
    ]


RegisterCodeGenerator.generated_source_info = property(_stable_generated_source_info)


THIS_DIR = Path(__file__).parent
DEFAULT_TOML = THIS_DIR.parent / "src" / "registers" / "can_fd_fi_registers.toml"
output_folder = THIS_DIR.parent / "gen"


def _find_repo_root() -> Path:
    """Walk up from this script until we find the repo's scripts/project-settings.sh."""
    for candidate in THIS_DIR.parents:
        if (candidate / "scripts" / "project-settings.sh").is_file():
            return candidate
    raise FileNotFoundError(
        "Could not locate scripts/project-settings.sh above "
        f"{THIS_DIR} — cannot determine the Rust application folder."
    )


def _copy_rust_to_app(rust_file: Path) -> None:
    """
    Copy the generated Rust register module into the Rust test application's src/generated/ folder.

    The destination is the SW_APPS_RUST_CAN_FD_FI_TEST variable from scripts/project-settings.sh.
    That variable is defined in terms of other shell variables, so we resolve it by sourcing the
    settings file (with PRJ_ROOT_DIR exported) rather than parsing a single line.
    """
    repo_root = _find_repo_root()
    settings = repo_root / "scripts" / "project-settings.sh"

    result = subprocess.run(
        [
            "bash",
            "-c",
            f'source "{settings}" && printf "%s" "$SW_APPS_RUST_CAN_FD_FI_TEST"',
        ],
        env={"PRJ_ROOT_DIR": str(repo_root)},
        capture_output=True,
        text=True,
        check=True,
    )
    app_dir = Path(result.stdout.strip())
    if not result.stdout.strip():
        raise RuntimeError(
            "SW_APPS_RUST_CAN_FD_FI_TEST resolved to an empty path from "
            f"{settings} — cannot copy the generated Rust module."
        )

    dest_dir = app_dir / "src" / "generated"
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest_file = dest_dir / rust_file.name
    shutil.copyfile(rust_file, dest_file)
    print(f"Copied generated Rust module to {dest_file}")



def main(input_folder: Path) -> None:

    """
    Create register VHDL artifacts.
    """

    register_list = from_toml(
        name="can_fd_fi", toml_file=input_folder
    )


    VhdlRegisterPackageGenerator(
        register_list=register_list, output_folder=output_folder / "hdl"
    ).create()


    VhdlRecordPackageGenerator(
        register_list=register_list, output_folder=output_folder / "hdl"
    ).create()


    VhdlAxiLiteWrapperGenerator(
        register_list=register_list, output_folder=output_folder / "hdl"
    ).create()


    VhdlSimulationReadWritePackageGenerator(
        register_list=register_list, output_folder=output_folder / "sim"
    ).create()


    VhdlSimulationCheckPackageGenerator(
        register_list=register_list, output_folder=output_folder / "sim"
    ).create()


    VhdlSimulationWaitUntilPackageGenerator(
       register_list=register_list, output_folder=output_folder / "sim"
    ).create()


    """
    Create register C++ artifacts.
    """


    CppInterfaceGenerator(
        register_list=register_list, output_folder=output_folder / "sw" / "include"
    ).create()


    CppHeaderGenerator(
        register_list=register_list, output_folder=output_folder / "sw" / "include"
    ).create()


    CppImplementationGenerator(register_list=register_list, output_folder=output_folder).create()


    """
    Create register Rust artifacts.
    """


    RustRegisterGenerator(
        register_list=register_list, output_folder=output_folder / "rust"
    ).create()

    # Copy the generated Rust module into the Rust test application so it consumes a local copy
    # (destination path comes from SW_APPS_RUST_CAN_FD_FI_TEST in scripts/project-settings.sh).
    _copy_rust_to_app(output_folder / "rust" / "can_fd_fi.rs")



if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("TOML Path not proived, using default value")
        toml_path = DEFAULT_TOML
    else:
        toml_path = Path(sys.argv[1])

    main(input_folder=toml_path)
